<<<<<<< HEAD
#include<pthread.h>
#include<sys/msg.h>
#include<signal.h>
#include<sys/types.h>
#include<unistd.h>
#include<fcntl.h>
#include<sys/stat.h>
#include<sys/shm.h>
#include<sys/ipc.h>
#include<sys/sem.h>
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
=======
#include<pthread.h>
#include<sys/msg.h>
#include<signal.h>
#include<sys/types.h>
#include<unistd.h>
#include<fcntl.h>
#include<sys/stat.h>
#include<sys/shm.h>
#include<sys/ipc.h>
#include<sys/sem.h>
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
>>>>>>> f52763f2638bddc9d525298d831e7e86bb093de9
